# Generated by Django 3.2.5 on 2021-07-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=12, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=12, max_digits=15)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord', to='map.color')),
            ],
        ),
    ]
